[dotfiles] New logging framework

diff --git a/dotfile_installer b/dotfile_installer
--- a/dotfile_installer
+++ b/dotfile_installer
@@ -62,15 +62,15 @@ _set_linktype() {
 }
 
 _test_source_file() {
-    _info "Checking if ${_CONF_NAME} exists in package"
+    log_info "Checking if ${_CONF_NAME} exists in package"
     if [ ! -f "${_LOC_FILE}" ]
     then
-        _warn "Source file not found. Will create empty symlink"
+        log_warn "Source file not found. Will create empty symlink"
     fi
 }
 
 _backup_target() {
-    _info "Checking if ${_CONF_FILE} exists"
+    log_info "Checking if ${_CONF_FILE} exists"
     if [ -f "${_CONF_FILE}" ]
     then
         _BACKUPNAME="${_BCK_FILE}"
@@ -79,29 +79,29 @@ _backup_target() {
             _BACKUPNAME="${_BCK_FILE}.${_BCKNO}"
             _BCKNO=$((_BCKNO+1))
         done
-        _warn "Target file found, saving to ${_BACKUPNAME}"
+        log_info "Target file found, saving to ${_BACKUPNAME}"
         if [ -L "${_CONF_FILE}" ]
         then
             REAL_CONF=$(realpath "${_CONF_FILE}")
-            ${SUDO} cp -v -R "${REAL_CONF}" "${_BACKUPNAME}"
-            ${SUDO} rm -v "${_CONF_FILE}"
+            ${SUDO} cp -R "${REAL_CONF}" "${_BACKUPNAME}"
+            ${SUDO} rm "${_CONF_FILE}"
         else
-            ${SUDO} mv -v "${_CONF_FILE}" "${_BACKUPNAME}"
+            ${SUDO} mv "${_CONF_FILE}" "${_BACKUPNAME}"
         fi
     else
-        ${SUDO} rm "${_CONF_FILE}"
-        _info "Target file not found"
+        ${SUDO} rm "${_CONF_FILE}" 2>/dev/null || true
+        log_info "Target file not found"
     fi
 }
 
 _backup_target_dir() {
-    _info "Checking if ${_CONF_DIR} exists"
+    log_info "Checking if ${_CONF_DIR} exists"
     if [ -d "${_CONF_DIR}" ]
     then
-        _warn "Target directory found, saving to ${_BCK_DIR}"
+        log_info "Target directory found, saving to ${_BCK_DIR}"
         $SUDO mv -v "${_CONF_DIR}" "${_BCK_DIR}"
     else
-        _info "Target directory not found"
+        log_info "Target directory not found"
     fi
 }
 
@@ -117,6 +117,33 @@ _log_installed() {
     fi
 }
 
+_real_install() {
+	local sudo="$1"
+	local linktype="$2"
+	local loc_file="$3"
+	local conf_file="$4"
+
+    # TODO: Test if the linktype is possible. Else fallback to a copy and warn
+    # user about it.
+	#
+	# Shellcheck gives a warning here asking to doublequote the linktype
+	# variable. However, that will break the ln command since the variable may
+	# be empty sometimes. Doublequoting will pass an empty parameter to ln
+	# causing the command to fail.
+    ${sudo} ln ${linktype}"${loc_file}" "${conf_file}"
+}
+
+_begin_install() {
+	log_all_n "white" "Installing: "
+	log_all_n "nc" "$(eval printf "%-15s" "$1")"
+	log_std ""
+}
+
+_end_install() {
+    _log_installed "$_LOC_FILE" "$_CONF_FILE" "$linktype"
+	log_all "green" "[Done]"
+}
+
 # Function: install_file()
 # Parameter List:
 #   $1 : Conf File Name
@@ -124,6 +151,7 @@ _log_installed() {
 #   $3 : Needs root privileges to install?
 #   $4 : Is a symlink? (Default: Yes)
 install_file() {
+	_begin_install "$@"
     local _CONF_NAME="$1"
     local _CONF_FILE=$(_get_conf_file "$2")
     local _BCK_FILE=${_CONF_FILE}.bck
@@ -131,19 +159,19 @@ install_file() {
 
     local SUDO=$(_check_sudo "$3")
     local linktype=$(_set_linktype "$4")
-    # TODO: Test if the linktype is possible. Else fallback to a copy and warn
-    # user about it.
 
     _test_source_file
     _backup_target
 
-    _info "Linking dotfile ${_CONF_NAME} to ${_CONF_FILE}"
-    ${SUDO} ln ${linktype}"${_LOC_FILE}" "${_CONF_FILE}"
-    _log_installed "$_LOC_FILE" "$_CONF_FILE" "$linktype"
-    echo ""
+    log_info "Linking dotfile ${_CONF_NAME} to ${_CONF_FILE}"
+	_real_install "${SUDO}" "${linktype}" "${_LOC_FILE}" "${_CONF_FILE}"
+	_end_install
 }
 
+# TODO: Use a param to end_install to cause a yellow warning or red failed
+# output
 install_private_file() {
+	_begin_install "$@"
     local _CONF_NAME="$1"
     local _CONF_FILE=$(_get_conf_file "$2")
     local _BCK_FILE=${_CONF_FILE}.bck
@@ -152,22 +180,22 @@ install_private_file() {
     local SUDO=$(_check_sudo "$3")
     local linktype=$(_set_linktype "$4")
 
-    _info "Checking if ${_LOC_FILE} is mounted"
+    log_info "Checking if ${_LOC_FILE} is mounted"
     if [[ ! -f "${_LOC_FILE}" ]]
     then
-        _warn "Private configuration file not found."
-        _info "Will continue and create symlink to location"
+        log_warn "Private configuration file not found."
+        log_info "Will continue and create symlink to location"
     else
         _backup_target
     fi
 
-    _info "Linking dotfile ${_CONF_NAME} to ${_CONF_FILE}"
-    ${SUDO} ln ${linktype}"${_LOC_FILE}" "${_CONF_FILE}"
-    _log_installed "$_LOC_FILE" "$_CONF_FILE" "$linktype"
-    echo ""
+    log_info "Linking dotfile ${_CONF_NAME} to ${_CONF_FILE}"
+	_real_install "${SUDO}" "${linktype}" "${_LOC_FILE}" "${_CONF_FILE}"
+	_end_install
 }
 
 install_directory() {
+	_begin_install "$@"
     local _CONF_NAME="$1"
     local _CONF_DIR=$(_get_conf_file "$2")
     local _BCK_DIR=${_CONF_DIR}bck
@@ -178,16 +206,24 @@ install_directory() {
 
     _backup_target_dir
 
-    _info "Linking dotfile ${_CONF_NAME} to ${_CONF_DIR}"
-    $SUDO ln ${linktype}"${_LOC_DIR}" "${_CONF_DIR}"
-    _log_installed "$_LOC_DIR" "$_CONF_DIR" "$linktype"
-    echo ""
+    _info "Linking directory ${_CONF_NAME} to ${_CONF_DIR}"
+	_real_install "${SUDO}" "${linktype}" "${_LOC_FILE}" "${_CONF_FILE}"
+	_end_install
 }
+
+depends() {
+    ./dotfiles -b "$PACKAGE_NAME" -d "$1"
+}
+
+
+################################################################################
+# Custom Functions for use by the dotfile package installers                   #
+################################################################################
 
 install_packages() {
 	if ! isarchlinux; then
-		_warn "System is not ArchLinux. Packages not installed."
-		_info "Please install $* manually"
+		log_warn "System is not ArchLinux. Packages not installed."
+		log_info "Please install $* manually"
 		return
 	fi
 
@@ -196,8 +232,8 @@ install_packages() {
 
 install_aur() {
     if ! isarchlinux; then
-		_warn "System is not ArchLinux. Packages not installed."
-		_info "Please install $1 manually"
+		log_warn "System is not ArchLinux. Packages not installed."
+		log_info "Please install $1 manually"
 		return
 	fi
 
@@ -211,16 +247,6 @@ install_aur() {
     popd
     popd
 }
-
-depends() {
-    ./dotfiles -b "$PACKAGE_NAME" -d "$1"
-}
-
-
-################################################################################
-# Custom Functions for use by the dotfile package installers                   #
-################################################################################
-
 safetouch() {
     if [ ! -f "$1" ]
     then
@@ -233,7 +259,7 @@ safetouch() {
 
 is_in_path() {
     exec_name="$1"
-    if ! which $exec_name &> /dev/null; then
+    if ! which "$exec_name" &> /dev/null; then
         return 1
     else
         return 0
diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -49,11 +49,13 @@
 set -e
 set -u
 set -o pipefail
+# set -x
 
-# Source the variables and functions for displaying coloured output
-source .bash_colours || exit
 # Soure the various functions that are called by the install scripts
 source dotfile_installer || exit
+
+# Logging Framework
+source .bash_logging || exit
 
 # Location and name of the log file
 LOGFILE="dotfiles.log"
@@ -62,26 +64,8 @@ TEMPDB="/tmp/dotfile_tmp"
 
 BASEPKG=""
 
-# Redirect fd 3 to the logfile and redirect STDERR to STDOUT. This is set up for
-# easier logging. Redirecting STDERR to STDOUT allows us to simply write a
-# single redirection against the commands and all their output will be logged,
-# including errors and warnings
-# TODO: Find a better way to redirect all output and log it. We should not
-# redirect STDERR to STDOUT for this
-exec 3>>$LOGFILE 2>&1
+log_init ${LOGFILE}
 
-# #######################################
-# Print a message to console AND write it to a logfile
-# Globals:
-#	None
-# Arguments:
-#   Text
-# Returns:
-#   None
-#######################################
-write_log() {
-    tee -a /dev/fd/3 <<< "$*"
-}
 
 # #######################################
 # Install a package as a dependency of another
@@ -97,14 +81,17 @@ install_dependency() {
     if [[ $BASEPKG == "" ]]; then
         exit 1
     fi
-    write_log "$(_info "Installing Dependency $1")"
+	log_std "=== New Log Entry: $(date) ==="
+    log_info "Installing Dependency $1"
     echo -e "\n## $1 -> $BASEPKG" > $TEMPDB
     install_package "$1"
 }
 
 install_direct() {
     pkgname=${1%/}
-    write_log "$(_info "Installing package $pkgname\n")"
+	log_std "=== New Log Entry: $(date) ==="
+	log_info "Installing package $pkgname"
+    # write_log "$(_info "Installing package $pkgname\n")"
     echo -e "\n## $pkgname" > $TEMPDB
     install_package "$pkgname"
 }
@@ -124,34 +111,35 @@ install_package() {
     local pkgname="$1"
     local pkgdir="Packages/$pkgname"
     local pkgbuild="$pkgdir/InstallScript"
-    echo "=== New Log Entry: $(date) ===" >> $LOGFILE
 
     if [[ -f $pkgbuild ]]
     then
         source "$pkgbuild"
     else
-        write_log "$(_error "Cannot find Install Script for $pkgname")"
+		log_error "Cannot find Install Script for $pkgname"
         return 2
     fi
     if [[ ! -d "$pkgdir" ]]
     then
-        write_log "$(_error "Unable to locate package $pkgname")"
+		log_error "Unable to locate package $pkgname"
         return 2
     fi
 
     if [[ $(type -t prepare) == "function" ]]
     then
-        prepare 2>&1 | tee -a /dev/fd/3
+		log_all "white" "Running Pre-Install Hooks"
+		log_all "nc" "$(eval prepare 2>&1)"
+		log_std ""
     fi
 
-    install 2>&1 | tee -a /dev/fd/3
+	log_user "nc" "$(eval install 2>&1)"
 
     if [[ $(type -t post_install) == "function" ]]
     then
-        post_install 2>&1 | tee -a /dev/fd/3
+		log_all "white" "\nRunning Post-Install Hooks"
+		log_all "nc" "$(eval post_install 2>&1)"
     fi
-    echo "=== End of Log Entry ===" >> $LOGFILE
-    echo "" >> $LOGFILE
+	log_std "=== End of Log Entry ==="
     cat $TEMPDB >> $INSTALL
 }
 
@@ -185,7 +173,7 @@ repository"
 # main()
 # The script begins here with parsing the command line arguments and invoking
 # the relevant functions
-while getopts "S:b:d:Qh" options
+while getopts "S:b:d:Qht" options
 do
     case $options in
         S) install_direct "$OPTARG";;
@@ -193,6 +181,7 @@ do
         d) install_dependency "$OPTARG";;
         Q) list_packages;;
         h) print_help;;
+		t) log_test;;
         *) print_help;;
    esac
 done
